export const AGENTS_START = "<!-- vendor-src:start -->";
export const AGENTS_END = "<!-- vendor-src:end -->";

export interface AgentsRepoLine {
	name: string;
	package: string;
	path: string;
	version?: string;
	ref?: string;
}

function normalizeDir(dir: string): string {
	return dir.replace(/\/$/, "") || "repos";
}

/**
 * Concise managed block for the project-root AGENTS.md.
 * Wording adapted from the Effect blog on vendoring source for coding agents.
 * Always lists packages so agents need not grep the tree.
 */
export function renderAgentsBlock(
	repos: AgentsRepoLine[],
	dir = "repos",
): string {
	const root = normalizeDir(dir);
	const lines = [
		AGENTS_START,
		"## Vendored Repositories",
		"",
		`This project vendors external repositories under \`${root}/\` (see \`${root}/AGENTS.md\`).`,
		"",
		"- Use vendored repositories as **read-only reference material** when working with related libraries",
		"- Prefer examples and patterns from the vendored source over generated guesses or web search results",
		`- Do not edit files under \`${root}/\` unless explicitly asked`,
		`- Do not import from \`${root}/\` — application code should continue importing from normal package dependencies`,
		"",
	];

	if (repos.length > 0) {
		for (const repo of repos) {
			const version = repo.version ? `@${repo.version}` : "";
			lines.push(
				`- \`${repo.package}${version}\` → \`${repo.path}\` — idiomatic usage, tests, module structure, and API design`,
			);
		}
		lines.push("");
	}

	lines.push(AGENTS_END);
	return lines.join("\n");
}

/** Full AGENTS.md content for the vendor directory itself (e.g. `repos/AGENTS.md`). */
export function renderVendorDirAgentsMd(
	repos: AgentsRepoLine[],
	dir = "repos",
): string {
	const root = normalizeDir(dir);
	const lines = [
		"# Vendored repositories",
		"",
		`This directory (\`${root}/\`) holds git-subtree checkouts of dependencies, managed by [vendor-src](https://www.npmjs.com/package/vendor-src) and pinned to the versions installed in this project.`,
		"",
		"Coding agents are better at exploring source than reading documentation. Prefer these trees over docs or `node_modules` when learning how a library is meant to be used.",
		"",
		"## How to use",
		"",
		"- Treat everything here as **read-only reference material**",
		"- Prefer examples and patterns from this source over generated guesses or web search results",
		"- Do not format, lint-fix, or mass-edit these trees",
		"- Do not import application code from these paths — keep importing the normal npm packages",
		`- Config: \`vendor-src.json\` (\`dir\` defaults to \`repos\`; this tree uses \`${root}\`)`,
		"",
	];

	if (repos.length > 0) {
		lines.push("## Checkouts");
		lines.push("");
		for (const repo of repos) {
			const pin =
				repo.version !== undefined
					? repo.ref
						? ` (\`${repo.package}@${repo.version}\`, tag \`${repo.ref}\`)`
						: ` (\`${repo.package}@${repo.version}\`)`
					: ` (\`${repo.package}\`)`;
			lines.push(
				`- \`${repo.name}/\`${pin} — inspect for idiomatic usage, tests, module structure, and API design`,
			);
		}
		lines.push("");
	} else {
		lines.push("_No packages vendored yet. Run `vendor-src add <package>`._");
		lines.push("");
	}

	lines.push("<!-- Generated by vendor-src; do not edit by hand. -->");
	lines.push("");
	return lines.join("\n");
}

/** Insert or replace the managed vendor-src block in AGENTS.md content. */
export function upsertAgentsBlock(
	existing: string | undefined,
	repos: AgentsRepoLine[],
	dir = "repos",
): string {
	const block = renderAgentsBlock(repos, dir);
	if (!existing || existing.trim().length === 0) {
		return `${block}\n`;
	}

	const start = existing.indexOf(AGENTS_START);
	const end = existing.indexOf(AGENTS_END);
	if (start !== -1 && end !== -1 && end > start) {
		const before = existing.slice(0, start).replace(/\s*$/, "\n\n");
		const after = existing.slice(end + AGENTS_END.length).replace(/^\s*/, "\n");
		return `${before}${block}${after}`.replace(/\n{3,}/g, "\n\n");
	}

	const trimmed = existing.replace(/\s*$/, "");
	return `${trimmed}\n\n${block}\n`;
}
