export const AGENTS_START = "<!-- vendor-src:start -->";
export const AGENTS_END = "<!-- vendor-src:end -->";

export interface AgentsRepoLine {
	name: string;
	package: string;
	path: string;
	version?: string;
	ref?: string;
}

function normalizeDir(dir: string): string {
	return dir.replace(/\/+$/, "");
}

function packageSpec(repo: AgentsRepoLine): string {
	return repo.version ? `${repo.package}@${repo.version}` : repo.package;
}

function refSuffix(repo: AgentsRepoLine): string {
	const spec = packageSpec(repo);
	return repo.ref && repo.ref !== spec ? ` (ref \`${repo.ref}\`)` : "";
}

/**
 * Concise managed block for the project-root AGENTS.md.
 * Usage intent + package inventory; don'ts live in `{dir}/AGENTS.md`.
 */
export function renderAgentsBlock(
	repos: AgentsRepoLine[],
	dir: string,
): string {
	const root = normalizeDir(dir);
	const lines = [AGENTS_START, "", "## Vendored Source", ""];

	if (repos.length === 0) {
		lines.push(
			`Dependency source is vendored under \`${root}/\` as read-only reference material for coding agents, pinned to the installed versions. Nothing is vendored yet — run \`vendor-src add <package>\`. See \`${root}/AGENTS.md\`.`,
			"",
		);
	} else {
		lines.push(
			`Source for this project's key dependencies is vendored under \`${root}/\`, pinned to the installed versions. When a question is about how one of these libraries actually behaves, read its vendored source — implementation, tests, examples — instead of relying on docs, memory, or web search. The trees are read-only reference material; see \`${root}/AGENTS.md\` before touching or citing them.`,
			"",
			"### Vendored packages",
			"",
		);
		for (const repo of repos) {
			lines.push(`- \`${packageSpec(repo)}\` → \`${repo.path}\``);
		}
		lines.push("");
	}

	lines.push(AGENTS_END);
	return lines.join("\n");
}

/** Full AGENTS.md content for the vendor directory itself (e.g. `.repos/AGENTS.md`). */
export function renderVendorDirAgentsMd(
	repos: AgentsRepoLine[],
	dir: string,
): string {
	const root = normalizeDir(dir);
	const lines = [
		"# Vendored Source",
		"",
		`This directory holds git-subtree checkouts of dependency source, pinned to the versions this project installs and managed by [vendor-src](https://www.npmjs.com/package/vendor-src). Configuration lives in \`vendor-src.json\` (\`dir\` is \`${root}\`).`,
		"",
		"Coding agents are better at reading source than at reading documentation. For anything about how a vendored library is meant to be used, this tree is the primary reference — above docs, above training memory, above search results.",
		"",
		"## How to use it",
		"",
		"- Prefer a pattern you can point to in this tree over one you recall or infer",
		"- Start from the package's own README, then its source and tests for intended usage",
		"- If a version here disagrees with the installed package, run `vendor-src check` / `vendor-src sync` rather than reasoning from a stale tree",
		"",
		"## Don'ts",
		"",
		`- **Don't edit** anything under \`${root}/\`. It is reference, not project code, and \`vendor-src sync\` overwrites local changes`,
		`- **Don't format, lint-fix, or codemod** these trees — exclude them from repo-wide autofix runs`,
		`- **Don't import from \`${root}/\`** — application code keeps importing the installed npm packages`,
		"- **Don't commit upstream-style fixes here** — patch the real dependency or open a PR upstream",
		"",
		"## Vendored packages",
		"",
	];

	if (repos.length === 0) {
		lines.push("_None yet. Run `vendor-src add <package>`._");
	} else {
		for (const repo of repos) {
			lines.push(
				`- \`${repo.name}/\` — \`${packageSpec(repo)}\`${refSuffix(repo)}`,
			);
		}
	}

	lines.push("");
	lines.push("<!-- Generated by vendor-src; do not edit by hand. -->");
	lines.push("");
	return lines.join("\n");
}

/** Insert or replace the managed vendor-src block in AGENTS.md content. */
export function upsertAgentsBlock(
	existing: string | undefined,
	repos: AgentsRepoLine[],
	dir: string,
): string {
	const block = renderAgentsBlock(repos, dir);
	if (!existing || existing.trim().length === 0) {
		return `${block}\n`;
	}

	const start = existing.indexOf(AGENTS_START);
	const end = existing.indexOf(AGENTS_END);
	if (start !== -1 && end !== -1 && end > start) {
		const before =
			start === 0 ? "" : existing.slice(0, start).replace(/\s*$/, "\n\n");
		const after = existing.slice(end + AGENTS_END.length).replace(/^\s*/, "\n");
		return `${before}${block}${after}`.replace(/\n{3,}/g, "\n\n");
	}

	const trimmed = existing.replace(/\s*$/, "");
	return `${trimmed}\n\n${block}\n`;
}

/** Strip the managed vendor-src block from AGENTS.md content, if present. */
export function removeAgentsBlock(existing: string): string {
	const start = existing.indexOf(AGENTS_START);
	const end = existing.indexOf(AGENTS_END);
	if (start === -1 || end === -1 || end < start) {
		return existing;
	}
	const before = existing.slice(0, start).replace(/\s*$/, "");
	const after = existing.slice(end + AGENTS_END.length).replace(/^\s*/, "");
	const joined = [before, after].filter((part) => part.length > 0).join("\n\n");
	return joined.length === 0 ? "" : `${joined.replace(/\s*$/, "")}\n`;
}
