export const AGENTS_START = "<!-- vendor-src:start -->";
export const AGENTS_END = "<!-- vendor-src:end -->";

export interface AgentsRepoLine {
	name: string;
	package: string;
	path: string;
	version?: string;
	ref?: string;
}

function normalizeDir(dir: string): string {
	return dir.replace(/\/$/, "") || "repos";
}

/**
 * Concise managed block for the project-root AGENTS.md.
 * Uses the configured vendor directory (default `repos`).
 */
export function renderAgentsBlock(
	repos: AgentsRepoLine[],
	dir = "repos",
): string {
	const root = normalizeDir(dir);
	const lines = [
		AGENTS_START,
		"## Vendored sources",
		"",
		`Read-only dependency checkouts under \`${root}/\` (details in \`${root}/AGENTS.md\`). Do not format, edit, or import from there — keep using the npm packages.`,
		"",
	];

	if (repos.length > 0) {
		for (const repo of repos) {
			lines.push(`- \`${repo.path}\` — \`${repo.package}\``);
		}
		lines.push("");
	}

	lines.push(AGENTS_END);
	return lines.join("\n");
}

/** Full AGENTS.md content for the vendor directory itself (e.g. `repos/AGENTS.md`). */
export function renderVendorDirAgentsMd(
	repos: AgentsRepoLine[],
	dir = "repos",
): string {
	const root = normalizeDir(dir);
	const lines = [
		"# Vendored repositories",
		"",
		`This directory (\`${root}/\`) holds [vendor-src](https://www.npmjs.com/package/vendor-src) git-subtree checkouts, pinned to the versions installed in this project.`,
		"",
		"## How to use",
		"",
		"- Prefer reading these trees over docs when exploring library APIs and behavior",
		"- Treat everything here as **read-only** — do not format, lint-fix, or mass-edit",
		"- Do not import application code from these paths; keep importing the normal npm packages",
		`- Config lives in \`vendor-src.json\` (\`dir\` defaults to \`repos\`; this tree uses \`${root}\`)`,
		"",
	];

	if (repos.length > 0) {
		lines.push("## Checkouts");
		lines.push("");
		for (const repo of repos) {
			const pin =
				repo.version !== undefined
					? ` @${repo.version}${repo.ref ? ` (\`${repo.ref}\`)` : ""}`
					: "";
			lines.push(`- \`${repo.name}/\` — \`${repo.package}\`${pin}`);
		}
		lines.push("");
	} else {
		lines.push("_No packages vendored yet. Run `vendor-src add <package>`._");
		lines.push("");
	}

	lines.push("<!-- Generated by vendor-src; do not edit by hand. -->");
	lines.push("");
	return lines.join("\n");
}

/** Insert or replace the managed vendor-src block in AGENTS.md content. */
export function upsertAgentsBlock(
	existing: string | undefined,
	repos: AgentsRepoLine[],
	dir = "repos",
): string {
	const block = renderAgentsBlock(repos, dir);
	if (!existing || existing.trim().length === 0) {
		return `${block}\n`;
	}

	const start = existing.indexOf(AGENTS_START);
	const end = existing.indexOf(AGENTS_END);
	if (start !== -1 && end !== -1 && end > start) {
		const before = existing.slice(0, start).replace(/\s*$/, "\n\n");
		const after = existing.slice(end + AGENTS_END.length).replace(/^\s*/, "\n");
		return `${before}${block}${after}`.replace(/\n{3,}/g, "\n\n");
	}

	const trimmed = existing.replace(/\s*$/, "");
	return `${trimmed}\n\n${block}\n`;
}
